export type DayanNetworkProfessionalModality = "presential" | "online" | "both";

export type DayanNetworkProfessionalSeed = {
  name: string;
  specialty: string;
  professionalType: "doctor" | "dentist" | "nutritionist" | "clinic" | "integrative_therapist";
  bio: string;
  city: string;
  state: string;
  addressLine: string;
  lat: string;
  lng: string;
  phone: string;
  email: string;
  whatsapp: string;
  modality: DayanNetworkProfessionalModality;
  active: number;
  photoUrl: string | null;
  crm: string | null;
  crn: string | null;
  crf: string | null;
};

export type DayanNetworkProfessionalRecommendation = DayanNetworkProfessionalSeed & {
  distanceKm: number | null;
  matchScore: number;
  matchReasons: string[];
};

export const dayanNetworkProfessionalSeeds: DayanNetworkProfessionalSeed[] = [
  {
    name: "Dra. Helena Duarte Martins",
    specialty: "Medicina integrativa e clínica geral",
    professionalType: "doctor",
    bio: "Atendimento integrativo com foco em metabolismo, energia, rotina alimentar e organização de próximos passos clínicos.",
    city: "Cianorte",
    state: "PR",
    addressLine: "Av. América, 1040 - Centro",
    lat: "-23.6632000",
    lng: "-52.6054000",
    phone: "(44) 3030-1101",
    email: "helena.martins@rededayan.example",
    whatsapp: "5544990011101",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: "CRM-PR 48210",
    crn: null,
    crf: null,
  },
  {
    name: "Dr. Murilo Azevedo Pinto",
    specialty: "Endocrinologia funcional",
    professionalType: "doctor",
    bio: "Acompanha pacientes com fadiga, resistência insulínica, composição corporal e queixas hormonais frequentes.",
    city: "Cianorte",
    state: "PR",
    addressLine: "Rua Piratininga, 721 - Zona 01",
    lat: "-23.6586000",
    lng: "-52.6031000",
    phone: "(44) 3030-1102",
    email: "murilo.pinto@rededayan.example",
    whatsapp: "5544990011102",
    modality: "presential",
    active: 1,
    photoUrl: null,
    crm: "CRM-PR 51783",
    crn: null,
    crf: null,
  },
  {
    name: "Nutri. Camila Sanches Prado",
    specialty: "Nutrição integrativa",
    professionalType: "nutritionist",
    bio: "Conduz planos alimentares práticos para saúde intestinal, emagrecimento saudável e melhora de disposição.",
    city: "Cianorte",
    state: "PR",
    addressLine: "Rua Ipiranga, 360 - Centro",
    lat: "-23.6611000",
    lng: "-52.6106000",
    phone: "(44) 3030-1103",
    email: "camila.prado@rededayan.example",
    whatsapp: "5544990011103",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: null,
    crn: "CRN-8 18342",
    crf: null,
  },
  {
    name: "Clínica Elo Vital Cianorte",
    specialty: "Clínica integrativa multiprofissional",
    professionalType: "clinic",
    bio: "Equipe fictícia para testes com medicina integrativa, nutrição, acompanhamento de exames e educação em saúde.",
    city: "Cianorte",
    state: "PR",
    addressLine: "Av. Goiás, 1550 - Centro",
    lat: "-23.6650000",
    lng: "-52.6120000",
    phone: "(44) 3030-1104",
    email: "contato.cianorte@rededayan.example",
    whatsapp: "5544990011104",
    modality: "presential",
    active: 1,
    photoUrl: null,
    crm: null,
    crn: null,
    crf: null,
  },
  {
    name: "Dr. Felipe Romano Barros",
    specialty: "Medicina do estilo de vida",
    professionalType: "doctor",
    bio: "Foco em sono, movimento, hábitos sustentáveis e prevenção cardiometabólica.",
    city: "Cianorte",
    state: "PR",
    addressLine: "Rua Constituição, 94 - Zona 02",
    lat: "-23.6557000",
    lng: "-52.6089000",
    phone: "(44) 3030-1105",
    email: "felipe.barros@rededayan.example",
    whatsapp: "5544990011105",
    modality: "online",
    active: 1,
    photoUrl: null,
    crm: "CRM-PR 56441",
    crn: null,
    crf: null,
  },
  {
    name: "Nutri. Renata Molinari Costa",
    specialty: "Nutrição esportiva e metabólica",
    professionalType: "nutritionist",
    bio: "Atua em performance, recomposição corporal, rotina alimentar e organização de suplementos de forma educativa.",
    city: "Cianorte",
    state: "PR",
    addressLine: "Rua Santos Dumont, 880 - Centro",
    lat: "-23.6595000",
    lng: "-52.6167000",
    phone: "(44) 3030-1106",
    email: "renata.costa@rededayan.example",
    whatsapp: "5544990011106",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: null,
    crn: "CRN-8 22015",
    crf: null,
  },
  {
    name: "Dra. Lúcia Noronha Lima",
    specialty: "Saúde da mulher integrativa",
    professionalType: "doctor",
    bio: "Acolhe queixas de ciclo, energia, sono, climatério e organização de perguntas para consulta especializada.",
    city: "Cianorte",
    state: "PR",
    addressLine: "Rua Abolição, 540 - Centro",
    lat: "-23.6673000",
    lng: "-52.6079000",
    phone: "(44) 3030-1107",
    email: "lucia.lima@rededayan.example",
    whatsapp: "5544990011107",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: "CRM-PR 60342",
    crn: null,
    crf: null,
  },
  {
    name: "Farm. André Valença Rocha",
    specialty: "Farmácia clínica e suplementação",
    professionalType: "integrative_therapist",
    bio: "Apoio educativo para revisão de interações, adesão, rotina de uso e organização de dúvidas sobre suplementos.",
    city: "Cianorte",
    state: "PR",
    addressLine: "Av. Maranhão, 1210 - Centro",
    lat: "-23.6624000",
    lng: "-52.5998000",
    phone: "(44) 3030-1108",
    email: "andre.rocha@rededayan.example",
    whatsapp: "5544990011108",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: null,
    crn: null,
    crf: "CRF-PR 18402",
  },
  {
    name: "Dra. Marina Peixoto Nogueira",
    specialty: "Medicina integrativa e longevidade",
    professionalType: "doctor",
    bio: "Organiza avaliação preventiva, marcadores metabólicos, disposição e planejamento de cuidado longitudinal.",
    city: "Cianorte",
    state: "PR",
    addressLine: "Rua XV de Novembro, 455 - Centro",
    lat: "-23.6579000",
    lng: "-52.6129000",
    phone: "(44) 3030-1109",
    email: "marina.nogueira@rededayan.example",
    whatsapp: "5544990011109",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: "CRM-PR 61228",
    crn: null,
    crf: null,
  },
  {
    name: "Dr. Saulo Benevides Acioly",
    specialty: "Clínica médica integrativa",
    professionalType: "doctor",
    bio: "Atendimento centrado em queixas de cansaço, inflamação percebida, sono e acompanhamento de exames.",
    city: "Sobral",
    state: "CE",
    addressLine: "Av. Dom José, 620 - Centro",
    lat: "-3.6884000",
    lng: "-40.3499000",
    phone: "(88) 3030-2101",
    email: "saulo.acioly@rededayan.example",
    whatsapp: "5588990012101",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: "CRM-CE 21840",
    crn: null,
    crf: null,
  },
  {
    name: "Dra. Clarissa Fontenele Maia",
    specialty: "Endocrinologia e metabolismo",
    professionalType: "doctor",
    bio: "Acompanha peso, glicemia, tireoide e sintomas hormonais com visão integrativa e educativa.",
    city: "Sobral",
    state: "CE",
    addressLine: "Rua Coronel Mont'Alverne, 318 - Centro",
    lat: "-3.6847000",
    lng: "-40.3526000",
    phone: "(88) 3030-2102",
    email: "clarissa.maia@rededayan.example",
    whatsapp: "5588990012102",
    modality: "presential",
    active: 1,
    photoUrl: null,
    crm: "CRM-CE 24618",
    crn: null,
    crf: null,
  },
  {
    name: "Nutri. Beatriz Linhares Farias",
    specialty: "Nutrição clínica funcional",
    professionalType: "nutritionist",
    bio: "Trabalha com saúde intestinal, organização alimentar e metas de energia de forma prática para o cotidiano.",
    city: "Sobral",
    state: "CE",
    addressLine: "Rua Oriano Mendes, 142 - Centro",
    lat: "-3.6910000",
    lng: "-40.3512000",
    phone: "(88) 3030-2103",
    email: "beatriz.farias@rededayan.example",
    whatsapp: "5588990012103",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: null,
    crn: "CRN-11 17422",
    crf: null,
  },
  {
    name: "Clínica Integrar Sobral",
    specialty: "Clínica integrativa multiprofissional",
    professionalType: "clinic",
    bio: "Base fictícia para triagem, consultas integrativas, nutrição e acompanhamento educativo de exames.",
    city: "Sobral",
    state: "CE",
    addressLine: "Av. Lúcia Sabóia, 750 - Centro",
    lat: "-3.6868000",
    lng: "-40.3472000",
    phone: "(88) 3030-2104",
    email: "contato.sobral@rededayan.example",
    whatsapp: "5588990012104",
    modality: "presential",
    active: 1,
    photoUrl: null,
    crm: null,
    crn: null,
    crf: null,
  },
  {
    name: "Dr. Tobias Carneiro Sá",
    specialty: "Medicina preventiva",
    professionalType: "doctor",
    bio: "Foco em prevenção, revisão de hábitos, risco cardiometabólico e planejamento de autocuidado viável.",
    city: "Sobral",
    state: "CE",
    addressLine: "Rua Jornalista Deolindo Barreto, 925 - Centro",
    lat: "-3.6932000",
    lng: "-40.3569000",
    phone: "(88) 3030-2105",
    email: "tobias.sa@rededayan.example",
    whatsapp: "5588990012105",
    modality: "online",
    active: 1,
    photoUrl: null,
    crm: "CRM-CE 25177",
    crn: null,
    crf: null,
  },
  {
    name: "Nutri. Isadora Melo Gurgel",
    specialty: "Nutrição materno-infantil integrativa",
    professionalType: "nutritionist",
    bio: "Atendimento educativo para mulheres, famílias e crianças, respeitando rotina, sintomas e orientação profissional.",
    city: "Sobral",
    state: "CE",
    addressLine: "Rua Viriato de Medeiros, 1008 - Centro",
    lat: "-3.6873000",
    lng: "-40.3540000",
    phone: "(88) 3030-2106",
    email: "isadora.gurgel@rededayan.example",
    whatsapp: "5588990012106",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: null,
    crn: "CRN-11 19003",
    crf: null,
  },
  {
    name: "Dra. Norma Vasconcelos Rios",
    specialty: "Saúde da mulher e metabolismo",
    professionalType: "doctor",
    bio: "Acolhe sintomas de ciclo, climatério, sono, energia e organização de exames para discussão médica.",
    city: "Sobral",
    state: "CE",
    addressLine: "Av. Dr. Guarany, 503 - Derby",
    lat: "-3.6835000",
    lng: "-40.3464000",
    phone: "(88) 3030-2107",
    email: "norma.rios@rededayan.example",
    whatsapp: "5588990012107",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: "CRM-CE 27601",
    crn: null,
    crf: null,
  },
  {
    name: "Farm. Roberto Cavalcante Leal",
    specialty: "Farmácia clínica integrativa",
    professionalType: "integrative_therapist",
    bio: "Apoia revisão educativa de rotina, horários, adesão e dúvidas sobre combinações de produtos e medicamentos.",
    city: "Sobral",
    state: "CE",
    addressLine: "Rua Cel. José Sabóia, 333 - Centro",
    lat: "-3.6899000",
    lng: "-40.3449000",
    phone: "(88) 3030-2108",
    email: "roberto.leal@rededayan.example",
    whatsapp: "5588990012108",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: null,
    crn: null,
    crf: "CRF-CE 9904",
  },
  {
    name: "Dra. Elisa Prado Albuquerque",
    specialty: "Medicina integrativa e sono",
    professionalType: "doctor",
    bio: "Acompanha queixas de insônia, fadiga, rotina noturna e hábitos ligados à saúde metabólica.",
    city: "Sobral",
    state: "CE",
    addressLine: "Rua Menino Deus, 457 - Centro",
    lat: "-3.6921000",
    lng: "-40.3485000",
    phone: "(88) 3030-2109",
    email: "elisa.albuquerque@rededayan.example",
    whatsapp: "5588990012109",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: "CRM-CE 28840",
    crn: null,
    crf: null,
  },
  {
    name: "Dr. Gustavo Yamada Ferraz",
    specialty: "Medicina integrativa e metabolismo",
    professionalType: "doctor",
    bio: "Atende queixas de energia, peso, sono, exames alterados e prevenção de risco cardiometabólico.",
    city: "Maringá",
    state: "PR",
    addressLine: "Av. Brasil, 4360 - Zona 01",
    lat: "-23.4208000",
    lng: "-51.9333000",
    phone: "(44) 3030-3101",
    email: "gustavo.ferraz@rededayan.example",
    whatsapp: "5544990013101",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: "CRM-PR 57101",
    crn: null,
    crf: null,
  },
  {
    name: "Dra. Patrícia Goulart Neri",
    specialty: "Endocrinologia funcional",
    professionalType: "doctor",
    bio: "Foco em tireoide, resistência insulínica, composição corporal e sintomas hormonais persistentes.",
    city: "Maringá",
    state: "PR",
    addressLine: "Av. Tiradentes, 1560 - Zona 01",
    lat: "-23.4227000",
    lng: "-51.9388000",
    phone: "(44) 3030-3102",
    email: "patricia.neri@rededayan.example",
    whatsapp: "5544990013102",
    modality: "presential",
    active: 1,
    photoUrl: null,
    crm: "CRM-PR 59012",
    crn: null,
    crf: null,
  },
  {
    name: "Nutri. Lucas Bittencourt Reis",
    specialty: "Nutrição funcional e esportiva",
    professionalType: "nutritionist",
    bio: "Acompanha rotina alimentar, performance, composição corporal e organização de metas sustentáveis.",
    city: "Maringá",
    state: "PR",
    addressLine: "Rua Neo Alves Martins, 1722 - Zona 03",
    lat: "-23.4270000",
    lng: "-51.9362000",
    phone: "(44) 3030-3103",
    email: "lucas.reis@rededayan.example",
    whatsapp: "5544990013103",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: null,
    crn: "CRN-8 21184",
    crf: null,
  },
  {
    name: "Clínica Horizonte Integrativo",
    specialty: "Clínica integrativa multiprofissional",
    professionalType: "clinic",
    bio: "Estrutura fictícia para testes com atendimento presencial, nutrição, medicina integrativa e acompanhamento longitudinal.",
    city: "Maringá",
    state: "PR",
    addressLine: "Av. Herval, 890 - Centro",
    lat: "-23.4243000",
    lng: "-51.9291000",
    phone: "(44) 3030-3104",
    email: "horizonte.maringa@rededayan.example",
    whatsapp: "5544990013104",
    modality: "presential",
    active: 1,
    photoUrl: null,
    crm: null,
    crn: null,
    crf: null,
  },
  {
    name: "Dr. Rafael Cordeiro Tavares",
    specialty: "Cardiologia preventiva",
    professionalType: "doctor",
    bio: "Apoia prevenção cardiovascular, pressão, colesterol, rotina de movimento e leitura organizada de exames.",
    city: "Maringá",
    state: "PR",
    addressLine: "Rua Santos Dumont, 2050 - Zona 01",
    lat: "-23.4189000",
    lng: "-51.9409000",
    phone: "(44) 3030-3105",
    email: "rafael.tavares@rededayan.example",
    whatsapp: "5544990013105",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: "CRM-PR 54108",
    crn: null,
    crf: null,
  },
  {
    name: "Nutri. Fernanda Koga Almeida",
    specialty: "Nutrição intestinal e imunometabolismo",
    professionalType: "nutritionist",
    bio: "Foco em sintomas digestivos, rotina alimentar, saciedade, energia e escolhas de compra mais conscientes.",
    city: "Maringá",
    state: "PR",
    addressLine: "Av. São Paulo, 1198 - Zona 01",
    lat: "-23.4215000",
    lng: "-51.9450000",
    phone: "(44) 3030-3106",
    email: "fernanda.almeida@rededayan.example",
    whatsapp: "5544990013106",
    modality: "online",
    active: 1,
    photoUrl: null,
    crm: null,
    crn: "CRN-8 23770",
    crf: null,
  },
  {
    name: "Dra. Bianca Massuda Freire",
    specialty: "Saúde da mulher integrativa",
    professionalType: "doctor",
    bio: "Atendimento voltado a ciclo, climatério, sintomas persistentes, sono e conversa médica mais preparada.",
    city: "Maringá",
    state: "PR",
    addressLine: "Rua Joubert de Carvalho, 730 - Zona 01",
    lat: "-23.4258000",
    lng: "-51.9418000",
    phone: "(44) 3030-3107",
    email: "bianca.freire@rededayan.example",
    whatsapp: "5544990013107",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: "CRM-PR 62240",
    crn: null,
    crf: null,
  },
  {
    name: "Farm. Marcelo Antunes Mori",
    specialty: "Farmácia clínica e cuidado integrativo",
    professionalType: "integrative_therapist",
    bio: "Ajuda a organizar rotinas de uso, revisar dúvidas e preparar conversa com médico ou nutricionista.",
    city: "Maringá",
    state: "PR",
    addressLine: "Av. Paraná, 510 - Zona 01",
    lat: "-23.4196000",
    lng: "-51.9341000",
    phone: "(44) 3030-3108",
    email: "marcelo.mori@rededayan.example",
    whatsapp: "5544990013108",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: null,
    crn: null,
    crf: "CRF-PR 20118",
  },
  {
    name: "Dra. Aline Ruggiero Castro",
    specialty: "Medicina integrativa e saúde mental",
    professionalType: "doctor",
    bio: "Acolhe relação entre ansiedade, sono, alimentação, rotina e sintomas físicos recorrentes.",
    city: "Maringá",
    state: "PR",
    addressLine: "Rua Néo Alves Martins, 2788 - Zona 01",
    lat: "-23.4302000",
    lng: "-51.9339000",
    phone: "(44) 3030-3109",
    email: "aline.castro@rededayan.example",
    whatsapp: "5544990013109",
    modality: "online",
    active: 1,
    photoUrl: null,
    crm: "CRM-PR 64803",
    crn: null,
    crf: null,
  },
  {
    name: "Nutri. Eduardo Villas Boas Lima",
    specialty: "Nutrição para longevidade",
    professionalType: "nutritionist",
    bio: "Trabalha com hábitos alimentares, marcadores de saúde e planos práticos para envelhecer melhor.",
    city: "Maringá",
    state: "PR",
    addressLine: "Av. Cerro Azul, 875 - Zona 02",
    lat: "-23.4318000",
    lng: "-51.9254000",
    phone: "(44) 3030-3110",
    email: "eduardo.lima@rededayan.example",
    whatsapp: "5544990013110",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: null,
    crn: "CRN-8 24629",
    crf: null,
  },
  {
    name: "Dra. Teresa Mendes Vilar",
    specialty: "Geriatria preventiva integrativa",
    professionalType: "doctor",
    bio: "Acompanha longevidade, autonomia, exames, sono, nutrição e risco de fragilidade de forma preventiva.",
    city: "Maringá",
    state: "PR",
    addressLine: "Av. Laguna, 1224 - Zona 03",
    lat: "-23.4332000",
    lng: "-51.9369000",
    phone: "(44) 3030-3111",
    email: "teresa.vilar@rededayan.example",
    whatsapp: "5544990013111",
    modality: "presential",
    active: 1,
    photoUrl: null,
    crm: "CRM-PR 51077",
    crn: null,
    crf: null,
  },
  {
    name: "Dr. Caio Mantovani Lopes",
    specialty: "Ortopedia preventiva e movimento",
    professionalType: "doctor",
    bio: "Orienta avaliação de dores recorrentes, movimento seguro, prevenção de lesões e retorno gradual à atividade.",
    city: "Maringá",
    state: "PR",
    addressLine: "Rua Santos Dumont, 1210 - Zona 01",
    lat: "-23.4169000",
    lng: "-51.9360000",
    phone: "(44) 3030-3112",
    email: "caio.lopes@rededayan.example",
    whatsapp: "5544990013112",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: "CRM-PR 66912",
    crn: null,
    crf: null,
  },
  {
    name: "Dra. Renata Bezerra Câmara",
    specialty: "Medicina integrativa e metabolismo",
    professionalType: "doctor",
    bio: "Atende fadiga, sintomas digestivos, ganho de peso, exames alterados e planejamento de rotina saudável.",
    city: "Natal",
    state: "RN",
    addressLine: "Av. Prudente de Morais, 3250 - Lagoa Nova",
    lat: "-5.8135000",
    lng: "-35.2057000",
    phone: "(84) 3030-4101",
    email: "renata.camara@rededayan.example",
    whatsapp: "5584990014101",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: "CRM-RN 11240",
    crn: null,
    crf: null,
  },
  {
    name: "Dr. Tiago Falcão Medeiros",
    specialty: "Endocrinologia e estilo de vida",
    professionalType: "doctor",
    bio: "Acompanha metabolismo, obesidade, resistência insulínica e hábitos sustentáveis para o dia a dia.",
    city: "Natal",
    state: "RN",
    addressLine: "Av. Hermes da Fonseca, 1300 - Tirol",
    lat: "-5.7994000",
    lng: "-35.2021000",
    phone: "(84) 3030-4102",
    email: "tiago.medeiros@rededayan.example",
    whatsapp: "5584990014102",
    modality: "presential",
    active: 1,
    photoUrl: null,
    crm: "CRM-RN 12871",
    crn: null,
    crf: null,
  },
  {
    name: "Nutri. Juliana Seabra Lins",
    specialty: "Nutrição clínica integrativa",
    professionalType: "nutritionist",
    bio: "Conduz organização alimentar para energia, digestão, emagrecimento saudável e rotina possível.",
    city: "Natal",
    state: "RN",
    addressLine: "Rua Mossoró, 421 - Tirol",
    lat: "-5.7957000",
    lng: "-35.2038000",
    phone: "(84) 3030-4103",
    email: "juliana.lins@rededayan.example",
    whatsapp: "5584990014103",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: null,
    crn: "CRN-6 17721",
    crf: null,
  },
  {
    name: "Clínica Ponte Vital Natal",
    specialty: "Clínica integrativa multiprofissional",
    professionalType: "clinic",
    bio: "Equipe fictícia para testes com triagem, atendimento presencial, nutrição e acompanhamento de saúde integrativa.",
    city: "Natal",
    state: "RN",
    addressLine: "Av. Afonso Pena, 950 - Tirol",
    lat: "-5.7919000",
    lng: "-35.2004000",
    phone: "(84) 3030-4104",
    email: "pontevital.natal@rededayan.example",
    whatsapp: "5584990014104",
    modality: "presential",
    active: 1,
    photoUrl: null,
    crm: null,
    crn: null,
    crf: null,
  },
  {
    name: "Dra. Larissa Albuquerque Dantas",
    specialty: "Saúde da mulher integrativa",
    professionalType: "doctor",
    bio: "Acolhe queixas de ciclo, climatério, energia, sono e conversa médica orientada por contexto.",
    city: "Natal",
    state: "RN",
    addressLine: "Rua Apodi, 800 - Tirol",
    lat: "-5.7897000",
    lng: "-35.2043000",
    phone: "(84) 3030-4105",
    email: "larissa.dantas@rededayan.example",
    whatsapp: "5584990014105",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: "CRM-RN 13980",
    crn: null,
    crf: null,
  },
  {
    name: "Nutri. Paula Montenegro Aires",
    specialty: "Nutrição esportiva e funcional",
    professionalType: "nutritionist",
    bio: "Apoia rotina alimentar, performance, composição corporal, disposição e escolhas práticas no mercado.",
    city: "Natal",
    state: "RN",
    addressLine: "Av. Roberto Freire, 1800 - Capim Macio",
    lat: "-5.8578000",
    lng: "-35.2029000",
    phone: "(84) 3030-4106",
    email: "paula.aires@rededayan.example",
    whatsapp: "5584990014106",
    modality: "online",
    active: 1,
    photoUrl: null,
    crm: null,
    crn: "CRN-6 18104",
    crf: null,
  },
  {
    name: "Dr. Bruno Salustino Paiva",
    specialty: "Cardiologia preventiva",
    professionalType: "doctor",
    bio: "Atua com pressão, risco cardiovascular, exames, movimento e prevenção apoiada por mudanças possíveis.",
    city: "Natal",
    state: "RN",
    addressLine: "Rua Raimundo Chaves, 1822 - Candelária",
    lat: "-5.8273000",
    lng: "-35.2182000",
    phone: "(84) 3030-4107",
    email: "bruno.paiva@rededayan.example",
    whatsapp: "5584990014107",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: "CRM-RN 15043",
    crn: null,
    crf: null,
  },
  {
    name: "Farm. Mirela Baracho Costa",
    specialty: "Farmácia clínica e suplementação",
    professionalType: "integrative_therapist",
    bio: "Apoia organização de rotina, adesão e dúvidas educativas sobre produtos, suplementos e segurança de uso.",
    city: "Natal",
    state: "RN",
    addressLine: "Av. Nascimento de Castro, 1666 - Lagoa Nova",
    lat: "-5.8110000",
    lng: "-35.2156000",
    phone: "(84) 3030-4108",
    email: "mirela.costa@rededayan.example",
    whatsapp: "5584990014108",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: null,
    crn: null,
    crf: "CRF-RN 4021",
  },
  {
    name: "Dra. Sofia Macedo Vieira",
    specialty: "Medicina integrativa e saúde mental",
    professionalType: "doctor",
    bio: "Trabalha conexão entre rotina, ansiedade, sono, alimentação e sintomas persistentes com escuta integrativa.",
    city: "Natal",
    state: "RN",
    addressLine: "Av. Senador Salgado Filho, 1559 - Lagoa Nova",
    lat: "-5.8195000",
    lng: "-35.2086000",
    phone: "(84) 3030-4109",
    email: "sofia.vieira@rededayan.example",
    whatsapp: "5584990014109",
    modality: "online",
    active: 1,
    photoUrl: null,
    crm: "CRM-RN 15708",
    crn: null,
    crf: null,
  },
  {
    name: "Nutri. Henrique Valério Nunes",
    specialty: "Nutrição intestinal",
    professionalType: "nutritionist",
    bio: "Foco em digestão, desconfortos alimentares, energia e organização de plano alimentar simples de seguir.",
    city: "Natal",
    state: "RN",
    addressLine: "Rua Ceará-Mirim, 520 - Tirol",
    lat: "-5.7903000",
    lng: "-35.2069000",
    phone: "(84) 3030-4110",
    email: "henrique.nunes@rededayan.example",
    whatsapp: "5584990014110",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: null,
    crn: "CRN-6 19082",
    crf: null,
  },
  {
    name: "Dra. Mirella Queiroz Pacheco",
    specialty: "Medicina integrativa e longevidade",
    professionalType: "doctor",
    bio: "Acompanha prevenção, qualidade de vida, exames, energia e planejamento de cuidado para envelhecer bem.",
    city: "Natal",
    state: "RN",
    addressLine: "Av. Romualdo Galvão, 2120 - Lagoa Nova",
    lat: "-5.8152000",
    lng: "-35.2129000",
    phone: "(84) 3030-4111",
    email: "mirella.pacheco@rededayan.example",
    whatsapp: "5584990014111",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: "CRM-RN 16190",
    crn: null,
    crf: null,
  },
  {
    name: "Dr. Vitor Galvão Sales",
    specialty: "Medicina do esporte integrativa",
    professionalType: "doctor",
    bio: "Atua com dor, movimento, treino, prevenção de lesões e retorno seguro à atividade física.",
    city: "Natal",
    state: "RN",
    addressLine: "Av. Engenheiro Roberto Freire, 2450 - Ponta Negra",
    lat: "-5.8698000",
    lng: "-35.1809000",
    phone: "(84) 3030-4112",
    email: "vitor.sales@rededayan.example",
    whatsapp: "5584990014112",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: "CRM-RN 16914",
    crn: null,
    crf: null,
  },
  {
    name: "Dr. Álvaro Meneses Furtado",
    specialty: "Cardiologia preventiva integrativa",
    professionalType: "doctor",
    bio: "Acompanha pressão, colesterol, risco cardiometabólico e rotina de movimento com foco preventivo e linguagem simples.",
    city: "Cianorte",
    state: "PR",
    addressLine: "Rua Humaitá, 612 - Centro",
    lat: "-23.6599000",
    lng: "-52.6061000",
    phone: "(44) 3030-1110",
    email: "alvaro.furtado@rededayan.example",
    whatsapp: "5544990011110",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: "CRM-PR 67210",
    crn: null,
    crf: null,
  },
  {
    name: "Dra. Maitê Cabral Soriano",
    specialty: "Cardiologia clínica e prevenção",
    professionalType: "doctor",
    bio: "Atua com prevenção cardiovascular, sintomas de palpitação, organização de exames e plano de hábitos acompanhável.",
    city: "Cianorte",
    state: "PR",
    addressLine: "Av. Paraíba, 1440 - Zona 01",
    lat: "-23.6644000",
    lng: "-52.6097000",
    phone: "(44) 3030-1111",
    email: "maite.soriano@rededayan.example",
    whatsapp: "5544990011111",
    modality: "presential",
    active: 1,
    photoUrl: null,
    crm: "CRM-PR 68422",
    crn: null,
    crf: null,
  },
  {
    name: "Dra. Vanessa Kury Nakamura",
    specialty: "Odontologia integrativa e sono",
    professionalType: "dentist",
    bio: "Cuida de saúde oral, bruxismo, respiração, sono e orientações de prevenção conectadas ao cuidado sistêmico.",
    city: "Cianorte",
    state: "PR",
    addressLine: "Rua Guararapes, 308 - Centro",
    lat: "-23.6618000",
    lng: "-52.6042000",
    phone: "(44) 3030-1112",
    email: "vanessa.nakamura@rededayan.example",
    whatsapp: "5544990011112",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: "CRO-PR 28110",
    crn: null,
    crf: null,
  },
  {
    name: "Dr. Pedro Sato Almeida",
    specialty: "Odontologia biológica preventiva",
    professionalType: "dentist",
    bio: "Atendimento odontológico preventivo com foco em gengiva, inflamação oral, hábitos e encaminhamento integrado quando necessário.",
    city: "Cianorte",
    state: "PR",
    addressLine: "Av. Santa Catarina, 755 - Centro",
    lat: "-23.6661000",
    lng: "-52.6111000",
    phone: "(44) 3030-1113",
    email: "pedro.almeida@rededayan.example",
    whatsapp: "5544990011113",
    modality: "presential",
    active: 1,
    photoUrl: null,
    crm: "CRO-PR 29401",
    crn: null,
    crf: null,
  },
  {
    name: "Dra. Luiza Motta Figueiredo",
    specialty: "Pediatria integrativa",
    professionalType: "doctor",
    bio: "Acompanha crianças e famílias em sono, alimentação, imunidade percebida, rotina e prevenção com cuidado acolhedor.",
    city: "Cianorte",
    state: "PR",
    addressLine: "Rua Fernão Dias, 456 - Zona 02",
    lat: "-23.6563000",
    lng: "-52.6068000",
    phone: "(44) 3030-1114",
    email: "luiza.figueiredo@rededayan.example",
    whatsapp: "5544990011114",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: "CRM-PR 69504",
    crn: null,
    crf: null,
  },
  {
    name: "Dr. Enzo Moreira Tanaka",
    specialty: "Pediatria preventiva e nutrição infantil",
    professionalType: "doctor",
    bio: "Atendimento pediátrico fictício para testes com alimentação, crescimento, sono, rotina e orientação familiar.",
    city: "Cianorte",
    state: "PR",
    addressLine: "Rua Padre Anchieta, 222 - Centro",
    lat: "-23.6607000",
    lng: "-52.6135000",
    phone: "(44) 3030-1115",
    email: "enzo.tanaka@rededayan.example",
    whatsapp: "5544990011115",
    modality: "online",
    active: 1,
    photoUrl: null,
    crm: "CRM-PR 70127",
    crn: null,
    crf: null,
  },
  {
    name: "Dr. Mateus Farias Lemos",
    specialty: "Cardiologia preventiva integrativa",
    professionalType: "doctor",
    bio: "Foco em risco cardiovascular, pressão, exames laboratoriais e mudanças de rotina possíveis para o paciente.",
    city: "Sobral",
    state: "CE",
    addressLine: "Rua Domingos Olímpio, 810 - Centro",
    lat: "-3.6908000",
    lng: "-40.3507000",
    phone: "(88) 3030-2110",
    email: "mateus.lemos@rededayan.example",
    whatsapp: "5588990012110",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: "CRM-CE 30110",
    crn: null,
    crf: null,
  },
  {
    name: "Dra. Yara Bezerra Ponte",
    specialty: "Cardiologia clínica e estilo de vida",
    professionalType: "doctor",
    bio: "Acompanha sintomas cardiovasculares, hipertensão, colesterol e organização de plano preventivo com linguagem acessível.",
    city: "Sobral",
    state: "CE",
    addressLine: "Av. Monsenhor Aloísio Pinto, 1180 - Dom Expedito",
    lat: "-3.6951000",
    lng: "-40.3558000",
    phone: "(88) 3030-2111",
    email: "yara.ponte@rededayan.example",
    whatsapp: "5588990012111",
    modality: "presential",
    active: 1,
    photoUrl: null,
    crm: "CRM-CE 30482",
    crn: null,
    crf: null,
  },
  {
    name: "Dra. Amanda Sales Aragão",
    specialty: "Odontologia integrativa e prevenção",
    professionalType: "dentist",
    bio: "Cuida de saúde bucal, gengiva, prevenção, bruxismo e sinais orais que podem dialogar com saúde sistêmica.",
    city: "Sobral",
    state: "CE",
    addressLine: "Rua Anahid Andrade, 525 - Centro",
    lat: "-3.6861000",
    lng: "-40.3533000",
    phone: "(88) 3030-2112",
    email: "amanda.aragao@rededayan.example",
    whatsapp: "5588990012112",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: "CRO-CE 11034",
    crn: null,
    crf: null,
  },
  {
    name: "Dr. Ítalo Monte Vasconcelos",
    specialty: "Odontologia biológica e sono",
    professionalType: "dentist",
    bio: "Atendimento odontológico fictício para testes com bruxismo, sono, respiração e cuidado oral preventivo.",
    city: "Sobral",
    state: "CE",
    addressLine: "Av. John Sanford, 2145 - Junco",
    lat: "-3.6789000",
    lng: "-40.3652000",
    phone: "(88) 3030-2113",
    email: "italo.vasconcelos@rededayan.example",
    whatsapp: "5588990012113",
    modality: "presential",
    active: 1,
    photoUrl: null,
    crm: "CRO-CE 11982",
    crn: null,
    crf: null,
  },
  {
    name: "Dra. Camila Holanda Nobre",
    specialty: "Pediatria integrativa",
    professionalType: "doctor",
    bio: "Acompanha alimentação infantil, sono, rotina familiar, prevenção e educação em saúde para pais e crianças.",
    city: "Sobral",
    state: "CE",
    addressLine: "Rua Maria Tomásia, 370 - Centro",
    lat: "-3.6881000",
    lng: "-40.3469000",
    phone: "(88) 3030-2114",
    email: "camila.nobre@rededayan.example",
    whatsapp: "5588990012114",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: "CRM-CE 31078",
    crn: null,
    crf: null,
  },
  {
    name: "Dr. Natan Correia Ximenes",
    specialty: "Pediatria preventiva e desenvolvimento",
    professionalType: "doctor",
    bio: "Atendimento pediátrico focado em desenvolvimento, rotina, queixas recorrentes e orientação familiar prática.",
    city: "Sobral",
    state: "CE",
    addressLine: "Rua Cel. Mont'Alverne, 909 - Centro",
    lat: "-3.6839000",
    lng: "-40.3515000",
    phone: "(88) 3030-2115",
    email: "natan.ximenes@rededayan.example",
    whatsapp: "5588990012115",
    modality: "online",
    active: 1,
    photoUrl: null,
    crm: "CRM-CE 31821",
    crn: null,
    crf: null,
  },
  {
    name: "Dra. Simone Arantes Kappel",
    specialty: "Odontologia integrativa e prevenção",
    professionalType: "dentist",
    bio: "Atendimento odontológico preventivo com foco em saúde oral, inflamação gengival, bruxismo e rotina de cuidados.",
    city: "Maringá",
    state: "PR",
    addressLine: "Rua Piratininga, 1188 - Zona 01",
    lat: "-23.4236000",
    lng: "-51.9376000",
    phone: "(44) 3030-3113",
    email: "simone.kappel@rededayan.example",
    whatsapp: "5544990013113",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: "CRO-PR 30712",
    crn: null,
    crf: null,
  },
  {
    name: "Dr. Mauro Nishida Porto",
    specialty: "Odontologia biológica e sono",
    professionalType: "dentist",
    bio: "Cuida de bruxismo, respiração, saúde oral e prevenção com visão integrada ao sono e hábitos do paciente.",
    city: "Maringá",
    state: "PR",
    addressLine: "Av. XV de Novembro, 980 - Centro",
    lat: "-23.4211000",
    lng: "-51.9319000",
    phone: "(44) 3030-3114",
    email: "mauro.porto@rededayan.example",
    whatsapp: "5544990013114",
    modality: "presential",
    active: 1,
    photoUrl: null,
    crm: "CRO-PR 31590",
    crn: null,
    crf: null,
  },
  {
    name: "Dra. Lívia Cançado Pires",
    specialty: "Pediatria integrativa",
    professionalType: "doctor",
    bio: "Acompanha crianças e famílias em alimentação, sono, desenvolvimento, rotina escolar e prevenção.",
    city: "Maringá",
    state: "PR",
    addressLine: "Rua Arthur Thomas, 640 - Zona 03",
    lat: "-23.4284000",
    lng: "-51.9398000",
    phone: "(44) 3030-3115",
    email: "livia.pires@rededayan.example",
    whatsapp: "5544990013115",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: "CRM-PR 70844",
    crn: null,
    crf: null,
  },
  {
    name: "Dr. Heitor Nóbrega Lacerda",
    specialty: "Pediatria preventiva e desenvolvimento",
    professionalType: "doctor",
    bio: "Atendimento pediátrico para rotina, crescimento, sintomas recorrentes e educação familiar com abordagem preventiva.",
    city: "Maringá",
    state: "PR",
    addressLine: "Av. Brasil, 5220 - Zona 01",
    lat: "-23.4192000",
    lng: "-51.9368000",
    phone: "(44) 3030-3116",
    email: "heitor.lacerda@rededayan.example",
    whatsapp: "5544990013116",
    modality: "online",
    active: 1,
    photoUrl: null,
    crm: "CRM-PR 71409",
    crn: null,
    crf: null,
  },
  {
    name: "Dra. Celina Medeiros Pacheco",
    specialty: "Odontologia integrativa e prevenção",
    professionalType: "dentist",
    bio: "Cuida de prevenção oral, gengiva, bruxismo, respiração e orientação de hábitos conectados à saúde geral.",
    city: "Natal",
    state: "RN",
    addressLine: "Av. Afonso Pena, 1205 - Tirol",
    lat: "-5.7908000",
    lng: "-35.2016000",
    phone: "(84) 3030-4113",
    email: "celina.pacheco@rededayan.example",
    whatsapp: "5584990014113",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: "CRO-RN 6012",
    crn: null,
    crf: null,
  },
  {
    name: "Dr. Otávio Maciel Rocha",
    specialty: "Odontologia biológica e sono",
    professionalType: "dentist",
    bio: "Atendimento odontológico preventivo para saúde oral, bruxismo, sono, respiração e sinais de inflamação bucal.",
    city: "Natal",
    state: "RN",
    addressLine: "Rua Trairi, 555 - Petrópolis",
    lat: "-5.7865000",
    lng: "-35.1999000",
    phone: "(84) 3030-4114",
    email: "otavio.rocha@rededayan.example",
    whatsapp: "5584990014114",
    modality: "presential",
    active: 1,
    photoUrl: null,
    crm: "CRO-RN 6488",
    crn: null,
    crf: null,
  },
  {
    name: "Dra. Helena Paiva Barreto",
    specialty: "Pediatria integrativa",
    professionalType: "doctor",
    bio: "Acompanha alimentação, sono, imunidade percebida, crescimento e dúvidas familiares com abordagem preventiva.",
    city: "Natal",
    state: "RN",
    addressLine: "Av. Miguel Castro, 1220 - Lagoa Nova",
    lat: "-5.8211000",
    lng: "-35.2158000",
    phone: "(84) 3030-4115",
    email: "helena.barreto@rededayan.example",
    whatsapp: "5584990014115",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: "CRM-RN 17611",
    crn: null,
    crf: null,
  },
  {
    name: "Dr. Rafael Saldanha Maia",
    specialty: "Pediatria preventiva e desenvolvimento",
    professionalType: "doctor",
    bio: "Atendimento pediátrico fictício para rotina, desenvolvimento, sono, alimentação e orientação de pais.",
    city: "Natal",
    state: "RN",
    addressLine: "Rua Seridó, 410 - Petrópolis",
    lat: "-5.7849000",
    lng: "-35.2012000",
    phone: "(84) 3030-4116",
    email: "rafael.maia@rededayan.example",
    whatsapp: "5584990014116",
    modality: "online",
    active: 1,
    photoUrl: null,
    crm: "CRM-RN 18152",
    crn: null,
    crf: null,
  },
  {
    name: "Dra. Mariana Prado Campos",
    specialty: "Medicina integrativa",
    professionalType: "doctor",
    bio: "Atendimento integrativo para rotina, energia, sono e organização de prioridades clínicas.",
    city: "Curitiba",
    state: "PR",
    addressLine: "Rua Comendador Araújo, 510 - Batel",
    lat: "-25.4372000",
    lng: "-49.2797000",
    phone: "(41) 3030-5101",
    email: "mariana.campos@rededayan.example",
    whatsapp: "5541990015101",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: "CRM-PR 54402",
    crn: null,
    crf: null,
  },
  {
    name: "Nutri. Rafael Nascimento Portela",
    specialty: "Nutrição integrativa",
    professionalType: "nutritionist",
    bio: "Acompanha rotina alimentar, emagrecimento, digestão e organização de metas realistas.",
    city: "Fortaleza",
    state: "CE",
    addressLine: "Av. Santos Dumont, 2828 - Aldeota",
    lat: "-3.7342000",
    lng: "-38.4936000",
    phone: "(85) 3030-5102",
    email: "rafael.portela@rededayan.example",
    whatsapp: "5585990015102",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: null,
    crn: "CRN-11 20112",
    crf: null,
  },
  {
    name: "Clínica Vida Serena João Pessoa",
    specialty: "Clínica integrativa multiprofissional",
    professionalType: "clinic",
    bio: "Atendimento fictício para testes de expansão regional com medicina integrativa e nutrição.",
    city: "João Pessoa",
    state: "PB",
    addressLine: "Av. Epitácio Pessoa, 1880 - Tambauzinho",
    lat: "-7.1195000",
    lng: "-34.8450000",
    phone: "(83) 3030-5103",
    email: "vidaserenajp@rededayan.example",
    whatsapp: "5583990015103",
    modality: "presential",
    active: 1,
    photoUrl: null,
    crm: null,
    crn: null,
    crf: null,
  },
  {
    name: "Dr. Leandro Araújo Vasques",
    specialty: "Endocrinologia funcional",
    professionalType: "doctor",
    bio: "Acompanha metabolismo, glicemia, tireoide e composição corporal com foco educativo.",
    city: "Londrina",
    state: "PR",
    addressLine: "Av. Higienópolis, 1600 - Centro",
    lat: "-23.3129000",
    lng: "-51.1628000",
    phone: "(43) 3030-5104",
    email: "leandro.vasques@rededayan.example",
    whatsapp: "5543990015104",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: "CRM-PR 60114",
    crn: null,
    crf: null,
  },
  {
    name: "Dra. Carolina Sampaio Reis",
    specialty: "Saúde da mulher integrativa",
    professionalType: "doctor",
    bio: "Acolhe sintomas hormonais, ciclo, sono e organização de exames para consulta.",
    city: "Recife",
    state: "PE",
    addressLine: "Av. Conselheiro Aguiar, 2333 - Boa Viagem",
    lat: "-8.1166000",
    lng: "-34.8962000",
    phone: "(81) 3030-5105",
    email: "carolina.reis@rededayan.example",
    whatsapp: "5581990015105",
    modality: "online",
    active: 1,
    photoUrl: null,
    crm: "CRM-PE 29881",
    crn: null,
    crf: null,
  },
  {
    name: "Nutri. Flávia Torreão Matos",
    specialty: "Nutrição funcional e intestinal",
    professionalType: "nutritionist",
    bio: "Foco em sintomas digestivos, energia, saciedade e rotina alimentar possível.",
    city: "Salvador",
    state: "BA",
    addressLine: "Av. Tancredo Neves, 1186 - Caminho das Árvores",
    lat: "-12.9812000",
    lng: "-38.4556000",
    phone: "(71) 3030-5106",
    email: "flavia.matos@rededayan.example",
    whatsapp: "5571990015106",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: null,
    crn: "CRN-5 22504",
    crf: null,
  },
  {
    name: "Dr. Marcelo Tavares Cunha",
    specialty: "Medicina preventiva e longevidade",
    professionalType: "doctor",
    bio: "Atendimento educativo para prevenção, exames, rotina e marcadores de saúde ao longo do tempo.",
    city: "São Paulo",
    state: "SP",
    addressLine: "Av. Paulista, 171 - Bela Vista",
    lat: "-23.5707000",
    lng: "-46.6450000",
    phone: "(11) 3030-5107",
    email: "marcelo.cunha@rededayan.example",
    whatsapp: "5511990015107",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: "CRM-SP 182441",
    crn: null,
    crf: null,
  },
  {
    name: "Clínica Raiz Integrativa Rio",
    specialty: "Clínica integrativa multiprofissional",
    professionalType: "clinic",
    bio: "Base fictícia para testes de atendimento em clínica integrativa, nutrição e cuidado longitudinal.",
    city: "Rio de Janeiro",
    state: "RJ",
    addressLine: "Rua Visconde de Pirajá, 550 - Ipanema",
    lat: "-22.9846000",
    lng: "-43.2055000",
    phone: "(21) 3030-5108",
    email: "raiz.rio@rededayan.example",
    whatsapp: "5521990015108",
    modality: "presential",
    active: 1,
    photoUrl: null,
    crm: null,
    crn: null,
    crf: null,
  },
];

export function normalizeSpecialtyText(value: string | null | undefined) {
  return (value ?? "")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase();
}

const BRAZILIAN_STATE_CODES = new Set([
  "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG",
  "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO",
]);

const CITY_PREFIX_PATTERN = /(?:^|[\s,.;:!?])(?:em|de|do|da|para|pra|no|na|nos|nas|cidade\s+de|municipio\s+de|município\s+de)\s+([A-Za-zÀ-ÿ][A-Za-zÀ-ÿ'’.\-]*(?:\s+(?:d[aeo]s?|e|[A-Za-zÀ-ÿ][A-Za-zÀ-ÿ'’.\-]*)){0,6})\s*(?:[-,/]\s*|\s+)([A-Za-z]{2})(?=$|[\s,.;:!?])/gi;
const CITY_STATE_PATTERN = /(?:^|[\s,.;:!?])([A-Za-zÀ-ÿ][A-Za-zÀ-ÿ'’.\-]*(?:\s+(?:d[aeo]s?|e|[A-Za-zÀ-ÿ][A-Za-zÀ-ÿ'’.\-]*)){0,6})\s*(?:[-,/]\s*|\s+)([A-Za-z]{2})(?=$|[\s,.;:!?])/gi;
const CITY_NAME_STOPWORDS = new Set([
  "profissional", "profissionais", "medico", "medicos", "medica", "medicas", "doutor", "doutora", "nutri", "nutricionista",
  "dentista", "terapeuta", "rede", "dayan", "ligado", "ligados", "ligada", "ligadas", "cidade", "municipio", "município",
  "perto", "proximo", "próximo", "proxima", "próxima", "aqui", "minha", "regiao", "região",
]);

function cleanCandidateCityName(value: string) {
  const compacted = value
    .replace(/\s+/g, " ")
    .replace(/^[\s,.;:!?-]+|[\s,.;:!?-]+$/g, "")
    .trim();
  const lastLocationIntro = compacted.match(/(?:^|\s)(?:em|no|na|nos|nas|para|pra)\s+([^,.;:!?]+)$/i);
  const candidate = lastLocationIntro?.[1] ?? compacted;

  return candidate
    .replace(/^(?:cidade|municipio|município)\s+de\s+/i, "")
    .trim();
}

function isValidCandidateCityName(value: string) {
  const normalized = normalizeSpecialtyText(cleanCandidateCityName(value)).replace(/[^a-z0-9]+/g, " ").trim();
  if (normalized.length < 3) return false;
  const words = normalized.split(/\s+/).filter(Boolean);
  if (words.length === 0 || words.length > 7) return false;
  return words.some((word) => !CITY_NAME_STOPWORDS.has(word));
}

function extractCityStateFromText(message: string): { city: string; state: string } | null {
  for (const pattern of [CITY_PREFIX_PATTERN, CITY_STATE_PATTERN]) {
    pattern.lastIndex = 0;
    let match: RegExpExecArray | null;
    while ((match = pattern.exec(message)) !== null) {
      const city = cleanCandidateCityName(match[1] ?? "");
      const state = (match[2] ?? "").trim().toUpperCase();
      if (BRAZILIAN_STATE_CODES.has(state) && isValidCandidateCityName(city)) {
        return { city, state };
      }
    }
  }
  return null;
}

function containsCityName(message: string, city: string) {
  const normalizedMessage = ` ${normalizeSpecialtyText(message).replace(/[^a-z0-9]+/g, " ").replace(/\s+/g, " ").trim()} `;
  const normalizedCity = normalizeSpecialtyText(city).replace(/[^a-z0-9]+/g, " ").replace(/\s+/g, " ").trim();
  return normalizedCity.length >= 3 && normalizedMessage.includes(` ${normalizedCity} `);
}

export function resolveDayanNetworkProfessionalLocationFromMessage(
  message: string | null | undefined,
  professionals: DayanNetworkProfessionalSeed[] = dayanNetworkProfessionalSeeds,
): { city: string; state?: string | null; source: "message_city_state" | "professional_base_city" } | null {
  const text = message?.trim();
  if (!text) return null;

  const explicitCityState = extractCityStateFromText(text);
  if (explicitCityState) return { ...explicitCityState, source: "message_city_state" };

  const activeProfessionals = professionals.filter((professional) => professional.active === 1);
  const matchedCities = activeProfessionals
    .filter((professional) => containsCityName(text, professional.city))
    .map((professional) => ({ city: professional.city, state: professional.state }));
  const uniqueMatches = Array.from(new Map(matchedCities.map((match) => [`${normalizeSpecialtyText(match.city)}|${match.state}`, match])).values());

  return uniqueMatches.length === 1
    ? { city: uniqueMatches[0].city, state: uniqueMatches[0].state, source: "professional_base_city" }
    : null;
}

export function inferSpecialtyFromNeed(text: string | null | undefined) {
  const normalized = normalizeSpecialtyText(text);
  if (/intestin|digest|estomag|reflux|constip|diarre|microbi/.test(normalized)) return "Nutrição intestinal";
  if (/emagrec|peso|obes|glic|insulin|diabet|metabol|tireoide/.test(normalized)) return "Endocrinologia funcional";
  if (/sono|inson|cansac|fadig|energia/.test(normalized)) return "Medicina integrativa e sono";
  if (/mulher|ciclo|menop|climater|hormon/.test(normalized)) return "Saúde da mulher integrativa";
  if (/coracao|pressao|cardio|colesterol/.test(normalized)) return "Cardiologia preventiva";
  if (/dor|joelho|ombro|coluna|treino|movimento|lesao/.test(normalized)) return "Medicina do esporte integrativa";
  if (/suplement|medicament|farmac|interacao/.test(normalized)) return "Farmácia clínica e suplementação";
  if (/aliment|nutri|dieta|compra|mercado/.test(normalized)) return "Nutrição integrativa";
  return "Medicina integrativa";
}

export function haversineKm(origin: { lat: number; lng: number }, destination: { lat: number; lng: number }) {
  const radiusKm = 6371;
  const toRad = (degrees: number) => (degrees * Math.PI) / 180;
  const dLat = toRad(destination.lat - origin.lat);
  const dLng = toRad(destination.lng - origin.lng);
  const lat1 = toRad(origin.lat);
  const lat2 = toRad(destination.lat);
  const a = Math.sin(dLat / 2) ** 2 + Math.cos(lat1) * Math.cos(lat2) * Math.sin(dLng / 2) ** 2;
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  return radiusKm * c;
}

export function rankDayanNetworkProfessionals(input: {
  city?: string | null;
  state?: string | null;
  specialty?: string | null;
  need?: string | null;
  lat?: number | null;
  lng?: number | null;
  limit?: number;
  professionals?: DayanNetworkProfessionalSeed[];
}): DayanNetworkProfessionalRecommendation[] {
  const desiredSpecialty = input.specialty?.trim() || inferSpecialtyFromNeed(input.need);
  const desired = normalizeSpecialtyText(desiredSpecialty);
  const city = normalizeSpecialtyText(input.city);
  const state = normalizeSpecialtyText(input.state);
  const origin = typeof input.lat === "number" && typeof input.lng === "number" ? { lat: input.lat, lng: input.lng } : null;
  const allActiveProfessionals = (input.professionals ?? dayanNetworkProfessionalSeeds).filter((professional) => professional.active === 1);
  const cityMatches = city
    ? allActiveProfessionals.filter((professional) => normalizeSpecialtyText(professional.city) === city && (!state || normalizeSpecialtyText(professional.state) === state))
    : [];
  const stateMatches = state
    ? allActiveProfessionals.filter((professional) => normalizeSpecialtyText(professional.state) === state)
    : [];
  const professionals = city ? cityMatches : stateMatches.length > 0 ? stateMatches : allActiveProfessionals;

  return professionals
    .map((professional) => {
      const professionalSpecialty = normalizeSpecialtyText(professional.specialty);
      const professionalCity = normalizeSpecialtyText(professional.city);
      const professionalState = normalizeSpecialtyText(professional.state);
      const distanceKm = origin
        ? haversineKm(origin, { lat: Number(professional.lat), lng: Number(professional.lng) })
        : null;
      const matchReasons: string[] = [];
      let matchScore = 30;

      if (desired && professionalSpecialty.includes(desired.split(" ")[0])) {
        matchScore += 30;
        matchReasons.push(`especialidade próxima de ${desiredSpecialty}`);
      }
      if (desired && professionalSpecialty.includes("integrativa")) {
        matchScore += 10;
        matchReasons.push("abordagem integrativa alinhada à Rede Dayan");
      }
      if (city && professionalCity === city) {
        matchScore += 80;
        matchReasons.push(`mesma cidade solicitada: ${professional.city}`);
      } else if (state && professionalState === state) {
        matchScore += 40;
        matchReasons.push(`mesmo estado solicitado: ${professional.state}`);
      }
      if (distanceKm !== null) {
        if (distanceKm <= 10) {
          matchScore += 25;
          matchReasons.push("muito próximo da localização informada");
        } else if (distanceKm <= 60) {
          matchScore += 18;
          matchReasons.push("próximo da região informada");
        } else if (distanceKm <= 250) {
          matchScore += 8;
          matchReasons.push("dentro de uma região ampliada");
        }
      }
      if (professional.modality === "online" || professional.modality === "both") {
        matchScore += 5;
        matchReasons.push("atende online ou em modelo híbrido");
      }
      if (matchReasons.length === 0) {
        matchReasons.push("profissional ativo na base fictícia da Rede Dayan");
      }

      return {
        ...professional,
        distanceKm: distanceKm === null ? null : Math.round(distanceKm * 10) / 10,
        matchScore,
        matchReasons,
      };
    })
    .sort((a, b) => {
      if (b.matchScore !== a.matchScore) return b.matchScore - a.matchScore;
      if (a.distanceKm === null && b.distanceKm === null) return a.name.localeCompare(b.name);
      if (a.distanceKm === null) return 1;
      if (b.distanceKm === null) return -1;
      return a.distanceKm - b.distanceKm;
    })
    .slice(0, input.limit ?? 6);
}
