from pathlib import Path

path = Path('/home/ubuntu/saude-integrativa-ia-dev/server/dayanNetworkProfessionalsSeed.ts')
text = path.read_text()
marker = '  {\n    name: "Dra. Mariana Prado Campos",\n'
if 'Dr. Álvaro Meneses Furtado' in text:
    print('Seed already enriched; no changes applied.')
    raise SystemExit(0)

extra_entries = '''  {
    name: "Dr. Álvaro Meneses Furtado",
    specialty: "Cardiologia preventiva integrativa",
    professionalType: "doctor",
    bio: "Acompanha pressão, colesterol, risco cardiometabólico e rotina de movimento com foco preventivo e linguagem simples.",
    city: "Cianorte",
    state: "PR",
    addressLine: "Rua Humaitá, 612 - Centro",
    lat: "-23.6599000",
    lng: "-52.6061000",
    phone: "(44) 3030-1110",
    email: "alvaro.furtado@rededayan.example",
    whatsapp: "5544990011110",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: "CRM-PR 67210",
    crn: null,
    crf: null,
  },
  {
    name: "Dra. Maitê Cabral Soriano",
    specialty: "Cardiologia clínica e prevenção",
    professionalType: "doctor",
    bio: "Atua com prevenção cardiovascular, sintomas de palpitação, organização de exames e plano de hábitos acompanhável.",
    city: "Cianorte",
    state: "PR",
    addressLine: "Av. Paraíba, 1440 - Zona 01",
    lat: "-23.6644000",
    lng: "-52.6097000",
    phone: "(44) 3030-1111",
    email: "maite.soriano@rededayan.example",
    whatsapp: "5544990011111",
    modality: "presential",
    active: 1,
    photoUrl: null,
    crm: "CRM-PR 68422",
    crn: null,
    crf: null,
  },
  {
    name: "Dra. Vanessa Kury Nakamura",
    specialty: "Odontologia integrativa e sono",
    professionalType: "dentist",
    bio: "Cuida de saúde oral, bruxismo, respiração, sono e orientações de prevenção conectadas ao cuidado sistêmico.",
    city: "Cianorte",
    state: "PR",
    addressLine: "Rua Guararapes, 308 - Centro",
    lat: "-23.6618000",
    lng: "-52.6042000",
    phone: "(44) 3030-1112",
    email: "vanessa.nakamura@rededayan.example",
    whatsapp: "5544990011112",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: "CRO-PR 28110",
    crn: null,
    crf: null,
  },
  {
    name: "Dr. Pedro Sato Almeida",
    specialty: "Odontologia biológica preventiva",
    professionalType: "dentist",
    bio: "Atendimento odontológico preventivo com foco em gengiva, inflamação oral, hábitos e encaminhamento integrado quando necessário.",
    city: "Cianorte",
    state: "PR",
    addressLine: "Av. Santa Catarina, 755 - Centro",
    lat: "-23.6661000",
    lng: "-52.6111000",
    phone: "(44) 3030-1113",
    email: "pedro.almeida@rededayan.example",
    whatsapp: "5544990011113",
    modality: "presential",
    active: 1,
    photoUrl: null,
    crm: "CRO-PR 29401",
    crn: null,
    crf: null,
  },
  {
    name: "Dra. Luiza Motta Figueiredo",
    specialty: "Pediatria integrativa",
    professionalType: "doctor",
    bio: "Acompanha crianças e famílias em sono, alimentação, imunidade percebida, rotina e prevenção com cuidado acolhedor.",
    city: "Cianorte",
    state: "PR",
    addressLine: "Rua Fernão Dias, 456 - Zona 02",
    lat: "-23.6563000",
    lng: "-52.6068000",
    phone: "(44) 3030-1114",
    email: "luiza.figueiredo@rededayan.example",
    whatsapp: "5544990011114",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: "CRM-PR 69504",
    crn: null,
    crf: null,
  },
  {
    name: "Dr. Enzo Moreira Tanaka",
    specialty: "Pediatria preventiva e nutrição infantil",
    professionalType: "doctor",
    bio: "Atendimento pediátrico fictício para testes com alimentação, crescimento, sono, rotina e orientação familiar.",
    city: "Cianorte",
    state: "PR",
    addressLine: "Rua Padre Anchieta, 222 - Centro",
    lat: "-23.6607000",
    lng: "-52.6135000",
    phone: "(44) 3030-1115",
    email: "enzo.tanaka@rededayan.example",
    whatsapp: "5544990011115",
    modality: "online",
    active: 1,
    photoUrl: null,
    crm: "CRM-PR 70127",
    crn: null,
    crf: null,
  },
  {
    name: "Dr. Mateus Farias Lemos",
    specialty: "Cardiologia preventiva integrativa",
    professionalType: "doctor",
    bio: "Foco em risco cardiovascular, pressão, exames laboratoriais e mudanças de rotina possíveis para o paciente.",
    city: "Sobral",
    state: "CE",
    addressLine: "Rua Domingos Olímpio, 810 - Centro",
    lat: "-3.6908000",
    lng: "-40.3507000",
    phone: "(88) 3030-2110",
    email: "mateus.lemos@rededayan.example",
    whatsapp: "5588990012110",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: "CRM-CE 30110",
    crn: null,
    crf: null,
  },
  {
    name: "Dra. Yara Bezerra Ponte",
    specialty: "Cardiologia clínica e estilo de vida",
    professionalType: "doctor",
    bio: "Acompanha sintomas cardiovasculares, hipertensão, colesterol e organização de plano preventivo com linguagem acessível.",
    city: "Sobral",
    state: "CE",
    addressLine: "Av. Monsenhor Aloísio Pinto, 1180 - Dom Expedito",
    lat: "-3.6951000",
    lng: "-40.3558000",
    phone: "(88) 3030-2111",
    email: "yara.ponte@rededayan.example",
    whatsapp: "5588990012111",
    modality: "presential",
    active: 1,
    photoUrl: null,
    crm: "CRM-CE 30482",
    crn: null,
    crf: null,
  },
  {
    name: "Dra. Amanda Sales Aragão",
    specialty: "Odontologia integrativa e prevenção",
    professionalType: "dentist",
    bio: "Cuida de saúde bucal, gengiva, prevenção, bruxismo e sinais orais que podem dialogar com saúde sistêmica.",
    city: "Sobral",
    state: "CE",
    addressLine: "Rua Anahid Andrade, 525 - Centro",
    lat: "-3.6861000",
    lng: "-40.3533000",
    phone: "(88) 3030-2112",
    email: "amanda.aragao@rededayan.example",
    whatsapp: "5588990012112",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: "CRO-CE 11034",
    crn: null,
    crf: null,
  },
  {
    name: "Dr. Ítalo Monte Vasconcelos",
    specialty: "Odontologia biológica e sono",
    professionalType: "dentist",
    bio: "Atendimento odontológico fictício para testes com bruxismo, sono, respiração e cuidado oral preventivo.",
    city: "Sobral",
    state: "CE",
    addressLine: "Av. John Sanford, 2145 - Junco",
    lat: "-3.6789000",
    lng: "-40.3652000",
    phone: "(88) 3030-2113",
    email: "italo.vasconcelos@rededayan.example",
    whatsapp: "5588990012113",
    modality: "presential",
    active: 1,
    photoUrl: null,
    crm: "CRO-CE 11982",
    crn: null,
    crf: null,
  },
  {
    name: "Dra. Camila Holanda Nobre",
    specialty: "Pediatria integrativa",
    professionalType: "doctor",
    bio: "Acompanha alimentação infantil, sono, rotina familiar, prevenção e educação em saúde para pais e crianças.",
    city: "Sobral",
    state: "CE",
    addressLine: "Rua Maria Tomásia, 370 - Centro",
    lat: "-3.6881000",
    lng: "-40.3469000",
    phone: "(88) 3030-2114",
    email: "camila.nobre@rededayan.example",
    whatsapp: "5588990012114",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: "CRM-CE 31078",
    crn: null,
    crf: null,
  },
  {
    name: "Dr. Natan Correia Ximenes",
    specialty: "Pediatria preventiva e desenvolvimento",
    professionalType: "doctor",
    bio: "Atendimento pediátrico focado em desenvolvimento, rotina, queixas recorrentes e orientação familiar prática.",
    city: "Sobral",
    state: "CE",
    addressLine: "Rua Cel. Mont'Alverne, 909 - Centro",
    lat: "-3.6839000",
    lng: "-40.3515000",
    phone: "(88) 3030-2115",
    email: "natan.ximenes@rededayan.example",
    whatsapp: "5588990012115",
    modality: "online",
    active: 1,
    photoUrl: null,
    crm: "CRM-CE 31821",
    crn: null,
    crf: null,
  },
  {
    name: "Dra. Simone Arantes Kappel",
    specialty: "Odontologia integrativa e prevenção",
    professionalType: "dentist",
    bio: "Atendimento odontológico preventivo com foco em saúde oral, inflamação gengival, bruxismo e rotina de cuidados.",
    city: "Maringá",
    state: "PR",
    addressLine: "Rua Piratininga, 1188 - Zona 01",
    lat: "-23.4236000",
    lng: "-51.9376000",
    phone: "(44) 3030-3113",
    email: "simone.kappel@rededayan.example",
    whatsapp: "5544990013113",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: "CRO-PR 30712",
    crn: null,
    crf: null,
  },
  {
    name: "Dr. Mauro Nishida Porto",
    specialty: "Odontologia biológica e sono",
    professionalType: "dentist",
    bio: "Cuida de bruxismo, respiração, saúde oral e prevenção com visão integrada ao sono e hábitos do paciente.",
    city: "Maringá",
    state: "PR",
    addressLine: "Av. XV de Novembro, 980 - Centro",
    lat: "-23.4211000",
    lng: "-51.9319000",
    phone: "(44) 3030-3114",
    email: "mauro.porto@rededayan.example",
    whatsapp: "5544990013114",
    modality: "presential",
    active: 1,
    photoUrl: null,
    crm: "CRO-PR 31590",
    crn: null,
    crf: null,
  },
  {
    name: "Dra. Lívia Cançado Pires",
    specialty: "Pediatria integrativa",
    professionalType: "doctor",
    bio: "Acompanha crianças e famílias em alimentação, sono, desenvolvimento, rotina escolar e prevenção.",
    city: "Maringá",
    state: "PR",
    addressLine: "Rua Arthur Thomas, 640 - Zona 03",
    lat: "-23.4284000",
    lng: "-51.9398000",
    phone: "(44) 3030-3115",
    email: "livia.pires@rededayan.example",
    whatsapp: "5544990013115",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: "CRM-PR 70844",
    crn: null,
    crf: null,
  },
  {
    name: "Dr. Heitor Nóbrega Lacerda",
    specialty: "Pediatria preventiva e desenvolvimento",
    professionalType: "doctor",
    bio: "Atendimento pediátrico para rotina, crescimento, sintomas recorrentes e educação familiar com abordagem preventiva.",
    city: "Maringá",
    state: "PR",
    addressLine: "Av. Brasil, 5220 - Zona 01",
    lat: "-23.4192000",
    lng: "-51.9368000",
    phone: "(44) 3030-3116",
    email: "heitor.lacerda@rededayan.example",
    whatsapp: "5544990013116",
    modality: "online",
    active: 1,
    photoUrl: null,
    crm: "CRM-PR 71409",
    crn: null,
    crf: null,
  },
  {
    name: "Dra. Celina Medeiros Pacheco",
    specialty: "Odontologia integrativa e prevenção",
    professionalType: "dentist",
    bio: "Cuida de prevenção oral, gengiva, bruxismo, respiração e orientação de hábitos conectados à saúde geral.",
    city: "Natal",
    state: "RN",
    addressLine: "Av. Afonso Pena, 1205 - Tirol",
    lat: "-5.7908000",
    lng: "-35.2016000",
    phone: "(84) 3030-4113",
    email: "celina.pacheco@rededayan.example",
    whatsapp: "5584990014113",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: "CRO-RN 6012",
    crn: null,
    crf: null,
  },
  {
    name: "Dr. Otávio Maciel Rocha",
    specialty: "Odontologia biológica e sono",
    professionalType: "dentist",
    bio: "Atendimento odontológico preventivo para saúde oral, bruxismo, sono, respiração e sinais de inflamação bucal.",
    city: "Natal",
    state: "RN",
    addressLine: "Rua Trairi, 555 - Petrópolis",
    lat: "-5.7865000",
    lng: "-35.1999000",
    phone: "(84) 3030-4114",
    email: "otavio.rocha@rededayan.example",
    whatsapp: "5584990014114",
    modality: "presential",
    active: 1,
    photoUrl: null,
    crm: "CRO-RN 6488",
    crn: null,
    crf: null,
  },
  {
    name: "Dra. Helena Paiva Barreto",
    specialty: "Pediatria integrativa",
    professionalType: "doctor",
    bio: "Acompanha alimentação, sono, imunidade percebida, crescimento e dúvidas familiares com abordagem preventiva.",
    city: "Natal",
    state: "RN",
    addressLine: "Av. Miguel Castro, 1220 - Lagoa Nova",
    lat: "-5.8211000",
    lng: "-35.2158000",
    phone: "(84) 3030-4115",
    email: "helena.barreto@rededayan.example",
    whatsapp: "5584990014115",
    modality: "both",
    active: 1,
    photoUrl: null,
    crm: "CRM-RN 17611",
    crn: null,
    crf: null,
  },
  {
    name: "Dr. Rafael Saldanha Maia",
    specialty: "Pediatria preventiva e desenvolvimento",
    professionalType: "doctor",
    bio: "Atendimento pediátrico fictício para rotina, desenvolvimento, sono, alimentação e orientação de pais.",
    city: "Natal",
    state: "RN",
    addressLine: "Rua Seridó, 410 - Petrópolis",
    lat: "-5.7849000",
    lng: "-35.2012000",
    phone: "(84) 3030-4116",
    email: "rafael.maia@rededayan.example",
    whatsapp: "5584990014116",
    modality: "online",
    active: 1,
    photoUrl: null,
    crm: "CRM-RN 18152",
    crn: null,
    crf: null,
  },
'''

if marker not in text:
    raise SystemExit(f'Marker not found: {marker!r}')
path.write_text(text.replace(marker, extra_entries + marker, 1))
print('Inserted additional priority-city Dayan Network professionals.')
